name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  install:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download data and model
        working-directory: ./dirty
        run: |
          wget cmu-itl.s3.amazonaws.com/dirty/dirt.tar.gz -O dirt.tar.gz
          tar -xzf dirt.tar.gz
          mkdir exp_runs/
          wget cmu-itl.s3.amazonaws.com/dirty/dirty_mt.ckpt -O exp_runs/dirty_mt.ckpt
          wandb offline
      - name: Infer and evaluate
        working-directory: ./dirty
        run: |
          python exp.py train --expname=eval_dirty_mt multitask_test_ci.xfmr.jsonnet --eval-ckpt exp_runs/dirty_mt.ckpt
          cat test_result.json
          cat test_result.json | jq ".test_retype_acc"
          cat test_result.json | jq ".test_rename_acc"
          cat test_result.json | jq ".test_retype_acc" | awk '{if ($1 < 0.999) exit 1}'
          cat test_result.json | jq ".test_rename_acc" | awk '{if ($1 < 0.999) exit 1}'
